# permissions for end users to edit ddbctldtpjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ddbctldtpjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ddbctl-dtp-helm-operator
    app.kubernetes.io/part-of: ddbctl-dtp-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: ddbctldtpjob-editor-role
rules:
- apiGroups:
  - ddbctl.dtp.charts.operators.jittakal.io
  resources:
  - ddbctldtpjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ddbctl.dtp.charts.operators.jittakal.io
  resources:
  - ddbctldtpjobs/status
  verbs:
  - get
